FROM t4dashi/photo_slam_noetic:dev

ARG ROS_DISTRO=noetic
ENV ROS_DISTRO=${ROS_DISTRO}


# Install ROS
RUN sudo apt update
RUN sudo apt install -y lsb-core curl
RUN sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
RUN sudo apt update
RUN sudo apt install -y python3-rosdep \
    python3-rosinstall \
    python3-rosinstall-generator \
    python3-wstool \
    python3-catkin-tools \
    build-essential
RUN sudo apt install -y ros-${ROS_DISTRO}-ros-base \
    ros-${ROS_DISTRO}-tf \
    ros-${ROS_DISTRO}-roslint

#RUN sudo rosdep init
RUN rosdep update

