version: "3.9"
services:
  # Base image containing dependencies.
  dev:
    image: t4dashi/photo_slam:dev
    container_name: photo_slam_dev
    #build:
      #context: ..
      #dockerfile: ./docker/Dockerfile.small
      #args:
        #- UID=${UID:-2000}
        #- GID=${UID:-2000}
        #- USERNAME=${USERNAME:-devuser}
      #target: dev
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host  
    ipc: host
    # Needed to display graphical applications
    environment:
      # Allows graphical programs in the container.
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb \
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    privileged: true
    volumes:
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - /dev/dri:/dev/dri:rw

      - ../src:/dev_ws/Photo-SLAM/src:rw
      - ../include:/dev_ws/Photo-SLAM/include:rw
      - ../CMakeLists.txt:/dev_ws/Photo-SLAM/CMakeLists.txt:rw
      - ../scripts:/dev_ws/Photo-SLAM/scripts:rw
      - ../examples:/dev_ws/Photo-SLAM/examples:rw
      - ../ORB-SLAM3/src:/dev_ws/Photo-SLAM/ORB-SLAM3/src:rw
      - ../ORB-SLAM3/include:/dev_ws/Photo-SLAM/ORB-SLAM3/include:rw

      - ../../results:/dev_ws/results:rw
      - ~/Desktop/thesis_utils/download_benchmark_data/dataset:/dev_ws/dataset:r

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: sleep infinity