# Stage 1: Use a pre-built OpenCV image with CUDA support
FROM t4dashi/opencv-cuda:11.8.0-ubuntu20.04 AS opencv_base

# Stage 2: Final Image
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04 AS dev

SHELL ["/bin/bash", "-c"]

ARG ROS_DISTRO=noetic
ENV ROS_DISTRO=${ROS_DISTRO}
ENV DEBIAN_FRONTEND=noninteractive

# Copy only the necessary OpenCV artifacts from the build stage
#COPY --from=opencv_base /usr/local /usr/local
COPY --from=opencv_base /usr/local/lib /usr/local/lib
COPY --from=opencv_base /usr/local/include /usr/local/include
COPY --from=opencv_base /usr/local/bin /usr/local/bin


# Install language
RUN apt-get update && apt-get install -y \
    locales \
    && locale-gen en_US.UTF-8 \
    && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*
ENV LANG=en_US.UTF-8

# Install timezone
RUN ln -fs /usr/share/zoneinfo/UTC /etc/localtime \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y tzdata \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*

# Install ROS
RUN apt-get update && apt-get install -y \
    curl \
    dirmngr \
    gnupg2 \
    lsb-release \
    sudo \
    && sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' \
    && curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - \
    && apt-get update && apt-get install -y \
    ros-noetic-desktop-full \
    && rm -rf /var/lib/apt/lists/*

# Install dev tools
RUN apt-get update && apt-get install -y \
    python3-rosdep \
    python3-rosinstall \
    python3-rosinstall-generator \
    python3-wstool \
    python3-catkin-tools \
    python3-pip \
    python3-pep8 \
    python3-autopep8 \
    pylint3 \
    build-essential \
    bash-completion \
    git \
    vim \
    software-properties-common \
    wget \
    && rm -rf /var/lib/apt/lists/* \
    && rosdep init || echo "rosdep already initialized"

RUN rosdep update

# gcc
RUN add-apt-repository ppa:ubuntu-toolchain-r/test -y

RUN apt-get install -y gcc-10 g++-10

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100

#RUN add-apt-repository universe
# Pangolin deps
RUN apt-get update && apt-get install -y \
    sudo \
    curl \
    zip \
    libeigen3-dev \
    libboost-all-dev \
    libjsoncpp-dev \
    libopengl-dev \
    mesa-utils \
    libglfw3-dev \
    libglm-dev \
    python3-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libswresample-dev \
    libssl-dev \
    libepoxy-dev \
    && rm -rf /var/lib/apt/lists/*


# Install CMake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.27.5/cmake-3.27.5-Linux-x86_64.sh -O /cmake-3.27.5.sh && \
    chmod +x /cmake-3.27.5.sh && \
    /cmake-3.27.5.sh --skip-license --prefix=/usr/local

# Create underlay workspace 
RUN mkdir -p /underlay_ws/src 
WORKDIR /underlay_ws/src
RUN git clone https://github.com/stevenlovegrove/Pangolin.git

WORKDIR /underlay_ws/src/Pangolin
RUN ./scripts/install_prerequisites.sh recommended || true
RUN cmake -B build 
RUN cmake --build build
RUN cmake --install build

RUN source /opt/ros/noetic/setup.bash \
    && catkin init 

# Build the base Catkin workspace
RUN cd /underlay_ws \
    && source /opt/ros/noetic/setup.bash \
    && catkin build --verbose

# libtorch
RUN cd / && \
    wget https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.0.1%2Bcu118.zip -O libtorch-cu118.zip && \
    unzip libtorch-cu118.zip && rm libtorch-cu118.zip
ENV Torch_DIR /libtorch/share/cmake/Torch



RUN apt-get update && apt-get install -y \
    libeigen3-dev \
    ros-${ROS_DISTRO}-hector-trajectory-server \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create overlay workspace
RUN mkdir -p /overlay_ws/src
COPY ../ /overlay_ws/src/photo_slam
WORKDIR /overlay_ws
RUN source /opt/ros/noetic/setup.bash \
    && source /underlay_ws/devel/setup.bash \
    && catkin init

RUN cd src/photo_slam/ORB-SLAM3/build \
    && cmake .. -DCMAKE_BUILD_TYPE=Release \
    && make -j8

RUN /bin/bash -c "source /opt/ros/noetic/setup.bash && source /underlay_ws/devel/setup.bash && catkin_make"

# Dev container arguments
ARG USERNAME=devuser
ARG UID=2000
ARG GID=${UID}

# Install extra tools for development
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    sudo \
    clangd \
    gdb \
    gdbserver \
    && apt clean && rm -rf /var/lib/apt/lists/*


# Create the sudoers directory
RUN mkdir -p /etc/sudoers.d

# Create new user and home directory
RUN groupadd --gid $GID $USERNAME \
    && useradd --uid ${GID} --gid ${UID} --create-home ${USERNAME} \
    && echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME} \
    && mkdir -p /home/${USERNAME} \
    && chown -R ${UID}:${GID} /home/${USERNAME} \
    && chown -R ${UID}:${GID} /overlay_ws

# Set the user
USER ${USERNAME}

COPY ./docker/entrypoint.sh /
RUN echo "source /entrypoint.sh" >> /home/${USERNAME}/.bashrc